"use client";
import { useMemo, useState } from "react";
import type { CSSProperties } from "react";
import styles from "./visual-lab.module.css";

type Locale = "en" | "fr";
type PaletteKey = "violet" | "blue" | "coral" | "forest" | "expressiveMulti" | "blueMulticolor" | "expressivePrimaries";
type Theme = "light" | "dark";
type Mode = "m3" | "expressive";
type Screen = "home" | "explore" | "tool";
type CategorySet = "current" | "vivid" | "blue";
type CategoryStyle = "soft" | "stripe" | "solid";
type SurfacePreset = "neutral" | "tonal" | "contrast";
type TypePreset = "geist" | "system" | "classic";
const palettes: Record<PaletteKey, { name: string; nameFr: string; seed: string; primary: string; secondary: string; tertiary: string; surface: string; primarySoft: string; darkPrimary: string; darkPrimarySoft: string; description: string; descriptionFr: string; darkSecondary?: string; darkTertiary?: string; darkOnPrimary?: string }> = {
  violet: { name: "Violet", nameFr: "Violet", seed: "#6750A4", primary: "#6750A4", secondary: "#625B71", tertiary: "#7D5260", surface: "#F7F2FA", primarySoft: "#EADDFF", darkPrimary: "#D0BCFF", darkPrimarySoft: "#4A3C63", description: "Distinctive and creative; close to familiar Material purple.", descriptionFr: "Créative et distinctive, proche du violet Material familier." },
  blue: { name: "Blue", nameFr: "Bleu", seed: "#386A9F", primary: "#386A9F", secondary: "#526070", tertiary: "#6B5778", surface: "#F2F6FB", primarySoft: "#D7E6FA", darkPrimary: "#A7C8F5", darkPrimarySoft: "#354A62", description: "Clear, dependable and more conventional.", descriptionFr: "Une identité classique, claire et rassurante." },
  forest: { name: "Teal + green", nameFr: "Turquoise + vert", seed: "#0F766E", primary: "#0F766E", secondary: "#3F6212", tertiary: "#B45309", surface: "#F3FAF7", primarySoft: "#CDEFE8", darkPrimary: "#5EEAD4", darkPrimarySoft: "#174A43", darkSecondary: "#B9F27C", darkTertiary: "#FDBA74", darkOnPrimary: "#003731", description: "A calmer nature-inspired direction with teal, green and amber accents.", descriptionFr: "Une direction plus apaisée, inspirée de la nature, entre turquoise, vert et ambre." },
  coral: { name: "Coral + teal", nameFr: "Corail + turquoise", seed: "#9A4057", primary: "#9A4057", secondary: "#42675F", tertiary: "#76558F", surface: "#FBF2F1", primarySoft: "#F8DCE1", darkPrimary: "#FFB2C0", darkPrimarySoft: "#5B303D", description: "A warm alternative that challenges the obvious choices.", descriptionFr: "Une alternative chaleureuse au corail et au turquoise." },
  expressiveMulti: { name: "Expressive multicolor", nameFr: "Expressive multicolore", seed: "#3F51B5", primary: "#3F51B5", secondary: "#7B1FA2", tertiary: "#00897B", surface: "#F8F7FF", primarySoft: "#E0E0FF", darkPrimary: "#C5C9FF", darkPrimarySoft: "#35385F", description: "Strong indigo, purple and teal for a playful, colorful toolbox.", descriptionFr: "Indigo, violet et turquoise soutenus pour une boîte à outils vivante." },
  blueMulticolor: { name: "Blue + vivid accents", nameFr: "Bleu + accents multicolores", seed: "#0B57D0", primary: "#0B57D0", secondary: "#7B1FA2", tertiary: "#00897B", surface: "#F5F8FF", primarySoft: "#D9E6FF", darkPrimary: "#A8C7FA", darkPrimarySoft: "#30466F", darkSecondary: "#D8B9FF", darkTertiary: "#72D9CB", darkOnPrimary: "#062E69", description: "Blue anchors the brand; saturated purple and teal are reserved for meaningful accents and categories.", descriptionFr: "Le bleu ancre l’identité ; le violet et le turquoise saturés servent d’accents et de couleurs de catégories." },
  expressivePrimaries: { name: "Expressive primary colors", nameFr: "Expressive bleu, rouge et jaune", seed: "#155EEF", primary: "#155EEF", secondary: "#D92D20", tertiary: "#F9C80E", surface: "#F7F9FC", primarySoft: "#DCE8FF", darkPrimary: "#A9C7FF", darkPrimarySoft: "#263E66", darkSecondary: "#FFB4A9", darkTertiary: "#F9D66B", darkOnPrimary: "#102B55", description: "True blue, red and yellow with calm surfaces; yellow is used as a soft accent surface, not tiny low-contrast text.", descriptionFr: "Du vrai bleu, rouge et jaune sur des surfaces reposantes ; le jaune sert de fond d’accent plutôt que de petit texte peu lisible." },
};
const copy = {
  en: {
    eyebrow:"Experimental playground · not production",title:"Find Loculary’s visual personality.",intro:"Change one dimension at a time. Compare the same interface across palettes, themes and expressive treatments before choosing what belongs in the real product.",paletteGuidance:"Google’s Material 3 examples use a baseline violet scheme, but M3 does not prescribe one universal palette. These are curated visual directions, not exported production tokens; category identity colors stay fixed so you can judge the full combination.",categoryColors:"Category identity colors",categoryColorsHelp:"These category colors are independent from the brand palette. Compare distinct color sets and visible treatments; the solid option uses matching foreground colors for readability.",
    palette:"Palette",theme:"Theme",style:"Visual language",viewport:"Preview width",categorySet:"Category color set",currentSet:"Current",vividSet:"Vivid multicolor",blueSet:"Blue-forward",categoryStyle:"Category treatment",softStyle:"Soft tint",stripeStyle:"Strong stripe",solidStyle:"Solid color",surfacePreset:"Surface palette",neutralSurface:"Neutral",tonalSurface:"Tonal",contrastSurface:"Higher contrast",typeface:"Typeface",geistTypeface:"Geist",systemTypeface:"System",classicTypeface:"Arial / sans-serif",language:"Preview language",light:"Light",dark:"Dark",classic:"Material 3",expressive:"M3 Expressive",desktop:"Desktop",tablet:"Tablet",mobile:"Mobile",
    home:"Home",explore:"Explore",tool:"Tool page",search:"What do you need to do?",searchButton:"Find a tool",quick:"Popular tasks",welcome:"A toolbox for your next idea",subhead:"Small tasks, useful tools, less friction.",browse:"Explore tools",
    results:"Suggested tools",resultOne:"Percentage calculator",resultTwo:"Image converter",resultThree:"Text cleaner",toolTitle:"Percentage calculator",toolDesc:"Calculate a percentage of any value.",value:"Value",percent:"Percentage",calculate:"Calculate",output:"Your result",
    components:"Component gallery",settings:"Account & preferences",settingsHelp:"Examples of options a user can turn on or off.",syncFavorites:"Sync favorites",syncFavoritesHelp:"Keep your favorites available on your account.",automaticTheme:"Use device theme",automaticThemeHelp:"Follow your phone or computer light/dark setting.",reducedMotion:"Reduce motion",reducedMotionHelp:"Limit non-essential animations.",switchOnLabel:"On",switchOffLabel:"Off",actions:"Actions & controls",forms:"Forms & selection",surfaces:"Surfaces & feedback",type:"Typography & shape",states:"Interaction states",filled:"Primary action",tonal:"Tonal action",outlined:"Outlined",textButton:"Text action",disabled:"Unavailable action",focus:"Keyboard focus",motion:"Replay motion",
    email:"Email address",choose:"Choose a category",selected:"Selected",chip:"Image tools",filter:"Filters",tabA:"Overview",tabB:"Details",cardTitle:"A useful result",cardText:"Keep the task clear and the next step obvious.",
    dialogTitle:"Ready to continue?",dialogText:"This is a sample dialog preview, not a real confirmation.",close:"Not now",confirm:"Continue",success:"Everything looks good",warning:"Check this value",error:"Enter a valid email address",
    composition:"Real-world compositions",compositionHelp:"Illustrative layouts using the selected tokens, not screenshots of the current production UI.",contrast:"Contrast review",contrastHelp:"Validate actual contrast before adopting a palette.",wcag:"Prototype swatches only — not a WCAG certification.",seed:"Seed color",
    note:"Nothing here changes Loculary’s production design. This is a decision aid; the final palette and style remain open.",closeDialog:"Close dialog",fieldHelp:"Shape, spacing and type respond to the selected visual language.",actionsHelp:"Use the controls above to compare the same components.",
  },
  fr: {
    eyebrow:"Laboratoire expérimental · hors production",title:"Trouvons la personnalité visuelle de Loculary.",intro:"Change une dimension à la fois. Compare la même interface selon les palettes, les thèmes et le style expressif avant de décider ce qui mérite d’entrer dans le vrai produit.",paletteGuidance:"Les exemples Material 3 de Google utilisent un violet de référence, mais M3 n’impose pas une palette universelle. Ces propositions sont des directions visuelles, pas des tokens de production exportés ; les couleurs des catégories restent fixes pour juger l’ensemble.",categoryColors:"Couleurs d’identité des catégories",categoryColorsHelp:"Les couleurs des catégories sont indépendantes de la palette de marque. Compare des jeux franchement différents et des traitements visibles ; les aplats utilisent une couleur de texte adaptée pour rester lisibles.",
    palette:"Palette",theme:"Thème",style:"Langage visuel",viewport:"Largeur d’aperçu",categorySet:"Jeu de couleurs des catégories",currentSet:"Actuel",vividSet:"Multicolore vif",blueSet:"Dominante bleue",categoryStyle:"Traitement des catégories",softStyle:"Teinte légère",stripeStyle:"Bande franche",solidStyle:"Aplat coloré",surfacePreset:"Palette des surfaces",neutralSurface:"Neutre",tonalSurface:"Teintée",contrastSurface:"Contraste renforcé",typeface:"Police de caractères",geistTypeface:"Geist",systemTypeface:"Système",classicTypeface:"Arial / sans-serif",language:"Langue de l’aperçu",light:"Clair",dark:"Sombre",classic:"Material 3",expressive:"M3 Expressive",desktop:"Ordinateur",tablet:"Tablette",mobile:"Mobile",
    home:"Accueil",explore:"Explorer",tool:"Page outil",search:"De quoi as-tu besoin ?",searchButton:"Trouver un outil",quick:"Actions populaires",welcome:"Une boîte à outils pour tes idées",subhead:"Des tâches simples, des outils utiles, moins de friction.",browse:"Explorer les outils",
    results:"Outils suggérés",resultOne:"Calcul de pourcentage",resultTwo:"Convertisseur d’image",resultThree:"Nettoyeur de texte",toolTitle:"Calcul de pourcentage",toolDesc:"Calcule un pourcentage de n’importe quelle valeur.",value:"Valeur",percent:"Pourcentage",calculate:"Calculer",output:"Ton résultat",
    components:"Galerie de composants",settings:"Compte et préférences",settingsHelp:"Exemples d’options que l’utilisateur peut activer ou désactiver.",syncFavorites:"Synchroniser les favoris",syncFavoritesHelp:"Retrouver les favoris sur son compte.",automaticTheme:"Suivre le thème de l’appareil",automaticThemeHelp:"Utiliser le mode clair ou sombre du téléphone ou de l’ordinateur.",reducedMotion:"Réduire les animations",reducedMotionHelp:"Limiter les animations non essentielles.",switchOnLabel:"Activé",switchOffLabel:"Désactivé",actions:"Actions et commandes",forms:"Formulaires et choix",surfaces:"Surfaces et retours",type:"Typographie et formes",states:"États d’interaction",filled:"Action principale",tonal:"Action tonale",outlined:"Contour",textButton:"Action texte",disabled:"Action indisponible",focus:"Focus clavier",motion:"Rejouer l’animation",
    email:"Adresse e-mail",choose:"Choisir une catégorie",selected:"Sélectionné",chip:"Outils image",filter:"Filtres",tabA:"Aperçu",tabB:"Détails",cardTitle:"Un résultat utile",cardText:"La tâche reste claire et la prochaine étape évidente.",
    dialogTitle:"Prêt à continuer ?",dialogText:"Ceci est un aperçu de dialogue, pas une vraie confirmation.",close:"Pas maintenant",confirm:"Continuer",success:"Tout semble correct",warning:"Vérifie cette valeur",error:"Saisis une adresse e-mail valide",
    composition:"Mises en situation",compositionHelp:"Compositions illustratives avec les tokens sélectionnés, pas des captures de l’interface actuelle.",contrast:"Vérification du contraste",contrastHelp:"Valide réellement les contrastes avant d’adopter une palette.",wcag:"Échantillons expérimentaux — aucune certification WCAG.",seed:"Couleur de départ",
    note:"Rien ici ne modifie le design de production de Loculary. C’est un outil d’aide à la décision ; palette et style restent à choisir.",closeDialog:"Fermer le dialogue",fieldHelp:"Formes, espacements et typographie suivent le langage visuel sélectionné.",actionsHelp:"Utilise les contrôles ci-dessus pour comparer les mêmes composants.",
  },
};

export default function VisualLab({ initialLocale }: { initialLocale: string }) {
  const [locale,setLocale]=useState<Locale>(initialLocale==="fr"?"fr":"en");
  const [paletteKey,setPaletteKey]=useState<PaletteKey>("violet");
  const [theme,setTheme]=useState<Theme>("light");
  const [mode,setMode]=useState<Mode>("expressive");
  const [screen,setScreen]=useState<Screen>("home");
  const [viewport,setViewport]=useState<"desktop"|"tablet"|"mobile">("desktop");
  const [categorySet,setCategorySet]=useState<CategorySet>("current");
  const [categoryStyle,setCategoryStyle]=useState<CategoryStyle>("soft");
  const [surfacePreset,setSurfacePreset]=useState<SurfacePreset>("neutral");
  const [typePreset,setTypePreset]=useState<TypePreset>("geist");
  const [dialogOpen,setDialogOpen]=useState(true);
  const [motionReplay,setMotionReplay]=useState(0);
  const [value,setValue]=useState("180");
  const [percent,setPercent]=useState("25");
  const [preferences,setPreferences]=useState({syncFavorites:true,automaticTheme:false,reducedMotion:true});
  const togglePreference=(key:keyof typeof preferences)=>setPreferences(current=>({...current,[key]:!current[key]}));
  const t=copy[locale];
  const palette=palettes[paletteKey];
  const isMulticolorPalette=paletteKey==="expressiveMulti"||paletteKey==="blueMulticolor"||paletteKey==="expressivePrimaries";
  const tokens=useMemo(()=> {
    const dark=theme==="dark";
    return {
      "--lab-bg":dark?(surfacePreset==="tonal"?"#14121A":surfacePreset==="contrast"?"#0B1020":"#111318"):(surfacePreset==="tonal"?palette.surface:surfacePreset==="contrast"?"#E8EDF7":"#F5F6FA"),
      "--lab-surface":dark?(surfacePreset==="tonal"?"#1D1A24":surfacePreset==="contrast"?"#151D31":"#1B1D24"):(surfacePreset==="tonal"?"#FFFFFF":surfacePreset==="contrast"?"#FDFEFF":"#FFFFFF"),
      "--lab-surface-2":dark?(surfacePreset==="tonal"?"#292532":surfacePreset==="contrast"?"#202B45":"#252832"):(surfacePreset==="tonal"?"#F1EDF6":surfacePreset==="contrast"?"#DDE6F4":"#EEF1F7"),
      "--lab-font":typePreset==="geist"?"var(--font-geist-sans), sans-serif":typePreset==="system"?"system-ui, -apple-system, \"Segoe UI\", sans-serif":"Arial, Helvetica, sans-serif",
      "--lab-text":dark?"#F2EFF7":"#1D1A22",
      "--lab-muted":dark?"#C4BECC":"#625D69",
      "--lab-outline":dark?"#494550":"#CAC4D0",
      "--lab-primary":dark?palette.darkPrimary:palette.primary,
      "--lab-on-primary":dark?(palette.darkOnPrimary ?? "#30234B"):"#FFFFFF",
      "--lab-primary-soft":dark?palette.darkPrimarySoft:palette.primarySoft,
      "--lab-secondary":dark?(palette.darkSecondary ?? "#D0C7DC"):palette.secondary,
      "--lab-tertiary":dark?(palette.darkTertiary ?? "#E8B9CF"):palette.tertiary,
      "--lab-radius":mode==="expressive"?"1.65rem":"0.8rem",
      "--lab-radius-small":mode==="expressive"?"1rem":"0.35rem",
      "--lab-motion":mode==="expressive"?"420ms":"180ms",
    } as CSSProperties & Record<string,string>;
  },[palette,paletteKey,mode,theme,surfacePreset,typePreset]);
  const amount=Number(value)*Number(percent)/100;
  const result=Number.isFinite(amount)?amount.toLocaleString(locale==="fr"?"fr-FR":"en-US",{maximumFractionDigits:3}):"—";
  const stageClass=[styles.stage,styles[viewport],theme==="dark"?styles.dark:styles.light,mode==="expressive"?styles.expressive:styles.classic].join(" ");
  const categoryItems = [
    { key: "calculations", name: locale === "fr" ? "Calculs" : "Calculations", icon: "％", currentLight: "#D92D20", currentDark: "#FF6B5E", vividLight: "#D32F2F", vividDark: "#FF625A", blueLight: "#2563EB", blueDark: "#60A5FA", onLight: "#FFFFFF", onDark: "#31100D", onBlueLight: "#FFFFFF", onBlueDark: "#10213A" },
    { key: "dates", name: locale === "fr" ? "Dates" : "Dates", icon: "◷", currentLight: "#A16207", currentDark: "#FDBA74", vividLight: "#F59E0B", vividDark: "#FBBF24", blueLight: "#0EA5E9", blueDark: "#38BDF8", onLight: "#241600", onDark: "#2A1D00", onBlueLight: "#082F49", onBlueDark: "#082F49" },
    { key: "computing", name: locale === "fr" ? "Informatique" : "Computing", icon: "⌘", currentLight: "#7A5AF8", currentDark: "#BDB4FE", vividLight: "#7C3AED", vividDark: "#A78BFA", blueLight: "#4F46E5", blueDark: "#818CF8", onLight: "#211044", onDark: "#211044", onBlueLight: "#FFFFFF", onBlueDark: "#171344" },
    { key: "images", name: locale === "fr" ? "Images" : "Images", icon: "▧", currentLight: "#C11574", currentDark: "#FDA4D5", vividLight: "#DB2777", vividDark: "#F472B6", blueLight: "#7C3AED", blueDark: "#C4B5FD", onLight: "#FFFFFF", onDark: "#30103D", onBlueLight: "#FFFFFF", onBlueDark: "#281044" },
    { key: "files", name: locale === "fr" ? "Fichiers" : "Files", icon: "▤", currentLight: "#0E7490", currentDark: "#67E8F9", vividLight: "#0891B2", vividDark: "#22D3EE", blueLight: "#0284C7", blueDark: "#38BDF8", onLight: "#062A35", onDark: "#062A35", onBlueLight: "#082F49", onBlueDark: "#082F49" },
    { key: "video", name: locale === "fr" ? "Vidéo" : "Video", icon: "▷", currentLight: "#0F766E", currentDark: "#5EEAD4", vividLight: "#059669", vividDark: "#34D399", blueLight: "#0D9488", blueDark: "#2DD4BF", onLight: "#062E25", onDark: "#06352E", onBlueLight: "#052E2B", onBlueDark: "#06352E" },
    { key: "development", name: locale === "fr" ? "Développement" : "Development", icon: "{ }", currentLight: "#155EEF", currentDark: "#9AB8FF", vividLight: "#2563EB", vividDark: "#818CF8", blueLight: "#1D4ED8", blueDark: "#93C5FD", onLight: "#FFFFFF", onDark: "#111B46", onBlueLight: "#FFFFFF", onBlueDark: "#10213A" },
  ];

  return <main data-category-set={categorySet} data-category-style={categoryStyle} data-surface-preset={surfacePreset} data-type-preset={typePreset} className={`${styles.lab} ${paletteKey==="expressivePrimaries"?styles.primaryTrio:""} ${theme==="dark"?styles.darkPalette:""} ${styles[`categoryStyle_${categoryStyle}`]}`} style={tokens}>
    <header className={styles.intro}>
      <div className={styles.introTop}><span className={styles.eyebrow}><span className={styles.sparkle} aria-hidden="true">✳</span>{t.eyebrow}</span>
        <label className={styles.compactControl}>{t.language}<select value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="fr">Français</option><option value="en">English</option></select></label>
      </div><h1>{t.title}</h1><p>{t.intro}</p>
    </header>
    <section className={styles.controlPanel} aria-label={t.palette}>
      <div><span className={styles.controlLabel}>{t.palette}</span><div className={styles.paletteOptions}>
        {(Object.entries(palettes) as [PaletteKey,typeof palettes[PaletteKey]][]).map(([key,item])=><button key={key} type="button" aria-pressed={paletteKey===key} className={paletteKey===key?styles.paletteSelected:styles.paletteOption} onClick={()=>setPaletteKey(key)}>
          <span className={styles.swatchGroup} aria-hidden="true"><i style={{background:item.primary}}/><i style={{background:item.secondary}}/><i style={{background:item.tertiary}}/></span><span className={styles.paletteText}><strong>{locale==="fr"?item.nameFr:item.name}</strong><small>{item.seed}</small></span>{paletteKey===key&&<span className={styles.check} aria-hidden="true">✓</span>}
        </button>)}
      </div><p className={styles.paletteDescription}>{locale==="fr"?palette.descriptionFr:palette.description}</p><p className={styles.paletteGuidance}>{t.paletteGuidance}</p></div>
      <div className={styles.controlRow}>
        <fieldset className={styles.segmentField}><legend>{t.theme}</legend><div className={styles.segmented}><button type="button" aria-pressed={theme==="light"} onClick={()=>setTheme("light")}>☀ {t.light}</button><button type="button" aria-pressed={theme==="dark"} onClick={()=>setTheme("dark")}>☾ {t.dark}</button></div></fieldset>
        <fieldset className={styles.segmentField}><legend>{t.style}</legend><div className={styles.segmented}><button type="button" aria-pressed={mode==="m3"} onClick={()=>setMode("m3")}>{t.classic}</button><button type="button" aria-pressed={mode==="expressive"} onClick={()=>setMode("expressive")}>{t.expressive}</button></div></fieldset>
        <fieldset className={styles.segmentField}><legend>{t.viewport}</legend><div className={styles.segmented}>{(["desktop","tablet","mobile"] as const).map(size=><button key={size} type="button" aria-pressed={viewport===size} onClick={()=>setViewport(size)}>{t[size]}</button>)}</div></fieldset>
        <fieldset className={styles.segmentField}><legend>{t.categorySet}</legend><div className={styles.segmented}><button type="button" aria-pressed={categorySet==="current"} onClick={()=>setCategorySet("current")}>{t.currentSet}</button><button type="button" aria-pressed={categorySet==="vivid"} onClick={()=>setCategorySet("vivid")}>{t.vividSet}</button><button type="button" aria-pressed={categorySet==="blue"} onClick={()=>setCategorySet("blue")}>{t.blueSet}</button></div></fieldset>
        <fieldset className={styles.segmentField}><legend>{t.categoryStyle}</legend><div className={styles.segmented}><button type="button" aria-pressed={categoryStyle==="soft"} onClick={()=>setCategoryStyle("soft")}>{t.softStyle}</button><button type="button" aria-pressed={categoryStyle==="stripe"} onClick={()=>setCategoryStyle("stripe")}>{t.stripeStyle}</button><button type="button" aria-pressed={categoryStyle==="solid"} onClick={()=>setCategoryStyle("solid")}>{t.solidStyle}</button></div></fieldset>
        <fieldset className={styles.segmentField}><legend>{t.surfacePreset}</legend><div className={styles.segmented}><button type="button" aria-pressed={surfacePreset==="neutral"} onClick={()=>setSurfacePreset("neutral")}>{t.neutralSurface}</button><button type="button" aria-pressed={surfacePreset==="tonal"} onClick={()=>setSurfacePreset("tonal")}>{t.tonalSurface}</button><button type="button" aria-pressed={surfacePreset==="contrast"} onClick={()=>setSurfacePreset("contrast")}>{t.contrastSurface}</button></div></fieldset>
        <fieldset className={styles.segmentField}><legend>{t.typeface}</legend><div className={styles.segmented}><button type="button" aria-pressed={typePreset==="geist"} onClick={()=>setTypePreset("geist")}>{t.geistTypeface}</button><button type="button" aria-pressed={typePreset==="system"} onClick={()=>setTypePreset("system")}>{t.systemTypeface}</button><button type="button" aria-pressed={typePreset==="classic"} onClick={()=>setTypePreset("classic")}>{t.classicTypeface}</button></div></fieldset>
      </div>
    </section>
    <section className={styles.previewSection} aria-labelledby="composition-title">
      <div className={styles.sectionHeading}><div><span className={styles.sectionKicker}>01 / {t.composition}</span><h2 id="composition-title">{t.composition}</h2><p>{t.compositionHelp}</p></div>
        <div className={styles.screenTabs} role="group" aria-label={t.composition}>{(["home","explore","tool"] as const).map(item=><button key={item} type="button" aria-pressed={screen===item} onClick={()=>setScreen(item)}>{t[item]}</button>)}</div>
      </div>
      <div className={stageClass} key={viewport+theme+mode+paletteKey}><div className={styles.mockApp}>
        <div className={styles.mockHeader}><div className={styles.brand}><span className={styles.brandMark}>L</span><strong>Loculary</strong></div><nav className={styles.mockNav} aria-label="Preview navigation"><span>{t.home}</span><span>{t.explore}</span><span aria-hidden="true">⌕</span></nav><button type="button" className={styles.avatar} aria-label="Profile preview">N</button></div>
        {screen==="home"&&<div className={styles.compositionContent}><div className={styles.heroText}><span className={styles.pill}>✦ {t.welcome}</span><h3>{t.welcome}</h3><p>{t.subhead}</p></div><div className={styles.searchBox}><span aria-hidden="true">⌕</span><span>{t.search}</span><button type="button">{t.searchButton} ↗</button></div><div className={styles.quickTasks}><span>{t.quick}</span><div><span>％ {t.resultOne}</span><span>▧ {t.resultTwo}</span><span>¶ {t.resultThree}</span></div></div><div className={styles.previewCards}><article><span className={styles.cardIcon}>✳</span><strong>{t.resultOne}</strong><p>25% × 180</p></article><article><span className={`${styles.cardIcon} ${isMulticolorPalette?styles.accentSecondary:""}`}>▧</span><strong>{t.resultTwo}</strong><p>PNG · JPG · WEBP</p></article></div></div>}
        {screen==="explore"&&<div className={styles.compositionContent}><div className={styles.exploreTitle}><span className={styles.pill}>{t.filter}</span><h3>{t.results}</h3><p>{t.subhead}</p></div><div className={styles.searchBox}><span>⌕</span><span>{t.search}</span></div><div className={styles.chipRow}><button type="button" className={styles.chipSelected}>{t.selected}</button><button type="button" className={`${styles.chip} ${isMulticolorPalette?styles.chipSecondary:""}`}>{t.chip}</button><button type="button" className={`${styles.chip} ${isMulticolorPalette?styles.chipTertiary:""}`}>{t.filter}</button></div><div className={styles.resultList}>{[t.resultOne,t.resultTwo,t.resultThree].map((name,index)=><article key={name}><span className={`${styles.cardIcon} ${isMulticolorPalette?(index===1?styles.accentSecondary:index===2?styles.accentTertiary:""):""}`}>{["％","▧","¶"][index]}</span><div><strong>{name}</strong><p>{t.cardText}</p></div><span aria-hidden="true">↗</span></article>)}</div></div>}
        {screen==="tool"&&<div className={styles.compositionContent}><div className={styles.toolIntro}><span className={styles.pill}>✦ {t.tool}</span><h3>{t.toolTitle}</h3><p>{t.toolDesc}</p></div><div className={styles.calculator}><label>{t.value}<input value={value} inputMode="decimal" onChange={e=>setValue(e.target.value)}/></label><label>{t.percent}<input value={percent} inputMode="decimal" onChange={e=>setPercent(e.target.value)}/></label><div className={styles.resultPanel}><span>{t.output}</span><strong>{result}</strong></div><button type="button">{t.calculate}</button></div></div>}
      </div>
      <section className={styles.categoryPreview} aria-labelledby="category-preview-title">
        <div className={styles.sectionHeading}><div><span className={styles.sectionKicker}>01B / {t.categoryColors}</span><h2 id="category-preview-title">{t.categoryColors}</h2><p>{t.categoryColorsHelp}</p></div></div>
        <div className={styles.categoryGrid}>
          {categoryItems.map((item) => <article key={item.key} className={styles.categoryCard} style={{ "--category-color": theme === "dark" ? (categorySet === "current" ? item.currentDark : categorySet === "vivid" ? item.vividDark : item.blueDark) : (categorySet === "current" ? item.currentLight : categorySet === "vivid" ? item.vividLight : item.blueLight), "--category-foreground": categorySet === "blue" ? (theme === "dark" ? item.onBlueDark : item.onBlueLight) : (theme === "dark" ? item.onDark : item.onLight) } as CSSProperties}>
            <span className={styles.categoryGlyph} aria-hidden="true">{item.icon}</span>
            <div><strong>{item.name}</strong><small>{theme === "dark" ? item.dark : item.light}</small></div>
          </article>)}
        </div>
      </section>
      </div>
    </section>
    <section className={styles.gallerySection} aria-labelledby="gallery-title"><div className={styles.sectionHeading}><div><span className={styles.sectionKicker}>02 / {t.components}</span><h2 id="gallery-title">{t.components}</h2><p>{t.actionsHelp}</p></div></div>
      <div className={styles.galleryGrid}>
        <article className={styles.galleryCard}><h3>{t.actions}</h3><div className={styles.buttonStack}><button type="button" className={styles.filled}>{t.filled}</button><button type="button" className={styles.tonal}>{t.tonal}</button><button type="button" className={styles.outlined}>{t.outlined}</button><button type="button" className={styles.textButton}>{t.textButton}</button><button type="button" className={styles.disabled} disabled>{t.disabled}</button></div><div className={styles.stateSamples}><button type="button" className={styles.focusSample}>{t.focus}</button><button type="button" className={styles.rippleSample} onClick={()=>setMotionReplay(n=>n+1)}>{t.motion}</button></div><p className={styles.helper}>{t.fieldHelp}</p><div key={motionReplay} className={styles.motionDemo} aria-hidden="true"><span>✦</span><span>✦</span><span>✦</span></div></article>
        <article className={styles.galleryCard}><h3>{t.forms}</h3><label className={styles.fieldLabel}>{t.email}<input type="email" placeholder="bonjour@loculary.com"/></label><label className={styles.fieldLabel}>{t.choose}<select defaultValue="images"><option value="images">{t.resultTwo}</option><option value="text">{t.resultThree}</option></select></label><div className={styles.chipRow}><button type="button" className={styles.chipSelected}>{t.selected} ✓</button><button type="button" className={`${styles.chip} ${isMulticolorPalette?styles.chipSecondary:""}`}>{t.chip}</button><button type="button" className={`${styles.chip} ${isMulticolorPalette?styles.chipTertiary:""}`}>{t.filter}</button></div><div className={styles.tabRow}><button type="button" className={styles.tabSelected}>{t.tabA}</button><button type="button" className={styles.tab}>{t.tabB}</button></div>
          <div className={styles.preferenceList}><div className={styles.preferenceHeading}><h4>{t.settings}</h4><p>{t.settingsHelp}</p></div>
            {([{key:"syncFavorites",title:t.syncFavorites,help:t.syncFavoritesHelp},{key:"automaticTheme",title:t.automaticTheme,help:t.automaticThemeHelp},{key:"reducedMotion",title:t.reducedMotion,help:t.reducedMotionHelp}] as const).map(item=><div className={styles.preferenceRow} key={item.key}><div className={styles.preferenceCopy}><strong>{item.title}</strong><p>{item.help}</p></div><button type="button" role="switch" aria-checked={preferences[item.key]} aria-label={item.title} className={preferences[item.key]?styles.switchOn:styles.switchOff} onClick={()=>togglePreference(item.key)}><span className={styles.switchThumb}/></button><span className={styles.preferenceState}>{preferences[item.key]?t.switchOnLabel:t.switchOffLabel}</span></div>)}
          </div></article>
        <article className={styles.galleryCard}><h3>{t.surfaces}</h3><div className={styles.infoCard}><span className={`${styles.cardIcon} ${isMulticolorPalette?styles.accentTertiary:""}`}>✳</span><strong>{t.cardTitle}</strong><p>{t.cardText}</p><button type="button" className={styles.textButton}>{t.browse} ↗</button></div><div className={styles.status} role="status"><span>✓</span>{t.success}</div><div className={styles.statusWarning}><span>!</span>{t.warning}</div><div className={styles.statusError} role="alert"><span>×</span>{t.error}</div></article>
        <article className={styles.galleryCard}><h3>{t.type}</h3><div className={styles.typeSample}><span>Display</span><strong>Ag</strong><h4>{t.welcome}</h4><p>{t.cardText}</p><small>Label · Supporting text</small></div><div className={styles.shapeRow}><span/><span/><span/><span/></div><p className={styles.helper}>{t.fieldHelp}</p></article>
      </div>
    </section>
    <section className={styles.gallerySection} aria-labelledby="states-title"><div className={styles.sectionHeading}><div><span className={styles.sectionKicker}>03 / {t.states}</span><h2 id="states-title">{t.states}</h2><p>{t.dialogText}</p></div><button type="button" className={styles.outlined} onClick={()=>setDialogOpen(true)}>{t.confirm} · dialog</button></div>
      {dialogOpen&&<div className={styles.dialogPreview} role="group" aria-label={t.states}><div className={styles.dialogIcon}>✦</div><h3>{t.dialogTitle}</h3><p>{t.dialogText}</p><div><button type="button" className={styles.textButton} onClick={()=>setDialogOpen(false)}>{t.close}</button><button type="button" className={styles.filled} onClick={()=>setDialogOpen(false)}>{t.confirm}</button></div></div>}
    </section>
    <footer className={styles.labFooter}><p>{t.note}</p><div><span>{t.seed}: <strong>{palette.seed}</strong></span><span>{t.contrast}</span><small>{t.contrastHelp} {t.wcag}</small></div></footer>
  </main>;
}
